### PR TITLE
Fix/44/refactor assign a task

### LINKED ISSUE #44: Refactor "assign a task" page
Disable 'assign a task' button and create a form

### PR DESCRIPTION
**Pull request by annakisel**
button 'assign a task' disabled, necessary information is transferred from one component to another, deleted modal window for full description and added a new router link for it

fix #44

### CODE REVIEW

File: src/app/assign-a-task/assign-a-task.component.ts [hunk 1]
```diff
@@ -16,4 +20,21 @@ export class AssignATaskComponent implements OnInit {
...
+    this.selectedId = event;
+  }
+
+  isItGroup(event) {
+    this.isGroupSelected = event;
+    console.log('isGroupSelected ', this.isGroupSelected);
+  }
+
+  onSubmit(value) {
+    console.log(value.inputDate._d.getTime());
```
Comment (alexey-kozlenkov) [inline src/app/assign-a-task/assign-a-task.component.ts]: Are you sure there is no other api? `_d` seems to me like a private prop
